backend:
  name: git-gateway
  branch: master

media_folder: "/static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "medewerkers"
    label: "Medewerkers"
    folder: "content/medewerkers" # The path to the folder where the documents are stored
    extension: "md"
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Naam", name: "name", widget: "string"}
      - {label: "Telefoon", name: "phone", widget: "string"}
      - {label: "Studies", name: "studies", widget: "list"}
      - {label: "Inhoud", name: "body", widget: "markdown"}
      - {label: "Afbeelding", name: "profile_picture", widget: "image", media_library: {config: {multiple: true}}}

  - name: "specialisaties" # Used in routes, e.g., /admin/collections/blog
    label: "Specialisaties" # Used in the UI
    folder: "content/specialisaties" # The path to the folder where the documents are stored
    extension: "md"
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Afbeelding", name: "featured_image", widget: "image", required: "false"}
      - {label: "Volgorde", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Hoofdpagina"
    name: "home"
    files:
      - label: "Welkomstekst"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: Title, name: title, widget: hidden}
          - {label: Afbeelding, name: featured_image, widget: hidden}
          - {label: Welkomstekst, name: body, widget: markdown}